# 服务器配置
server:
  port: 9001
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理；
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  profiles:
    active: dev
  application:
    name: sa-token-auth


  redis:
    database: 0
    port: 6379
    host: www.gavinwish.xyz
    password:


  cloud:
    nacos:
      # nacos 地址
      server-addr: www.gavinwish.xyz:8848
      discovery:
        group: default
        namespace: default
      config:
        group: default
        namespace: default
        file-extension: yml

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  # timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-head: true