server:
  port: 9000

spring:
  application:
    name: springboot-cache
  devtools:
    livereload:
      port: 10000
  # 数据库链接
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # 数据库链接池
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
  # redis缓存
  redis:
    host: localhost
    port: 6379
#  cache:
#    type: redis

# mybatis-plus配置
mybatis-plus:
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
    # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      gavin:
        cache: debug
